title: Public Writing
theme: minima
markdown: kramdown
sass:
  style: compressed
  
# Only include pages you want in the top-right menu
header_pages: []

# _config.yml
sass:
  style: compressed
# Add this line if not already included
defaults:
  -
    scope:
      path: ""
    values:
      css: "/assets/css/custom.css"
