title: Public Writing
theme: minima
markdown: kramdown

# Pages to show in the top-right menu
header_pages: []  # empty so no link appears

# SASS config
sass:
  style: compressed

# Optional: custom CSS
defaults:
  -
    scope:
      path: ""
    values:
      css: "/assets/css/custom.css"
